### ISSUE TITLE
Update jade version

### ISSUE THREAD

**Issue by blakeembrey** [jadejs/then-jade#12]
I'm running into some issues that were fixed at the beginning of the year, but this module is pegged at `1.3.0` which means I can't receive the updates.

**Comment by jeromew** [comment]
@ForbesLindesay I upgraded then-jade to 1.11.0. could you please re-activate `then-jade` on travis ? It seems that travis lost the project when it migrated from `then` to `jadejs` and travis says 

    organization: jade
    Sorry, but we can't find any repositories you have admin access to.
    You require admin rights to enable these repositories

**Comment by jeromew** [comment]
@ForbesLindesay I may have misunderstood something travis launched the tests on the new tag + the travis badge was still pointing to `then` org. Don't spend time on this.
